// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./components/ApplicationLogo.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    DropdownLink: typeof import('./components/DropdownLink.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    InputError: typeof import('./components/InputError.vue')['default']
    Label: typeof import('./components/Label.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    ResponsiveNavLink: typeof import('./components/ResponsiveNavLink.vue')['default']
    ValidationErrors: typeof import('./components/ValidationErrors.vue')['default']
  }
}
